[workspace]
members = ["backend", "frontend"]

# --- Backend (Django) ---
[service.backend]
root = "backend"
build = """
pip install --upgrade pip
pip install -r requirements.txt
python manage.py collectstatic --noinput
python manage.py migrate --noinput
"""
start = "gunicorn core.wsgi:application --bind 0.0.0.0:${PORT}"

# --- Frontend (React static) ---
[service.frontend]
root = "frontend"

[service.web]
root = "."