[workspace]
members = ["backend", "frontend"]

[service.backend]
root = "backend"
build = """
pip install --upgrade pip
pip install -r requirements.txt
python manage.py collectstatic --noinput
python manage.py migrate --noinput
"""
start = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"

[service.frontend]
root = "frontend"
build = "npm ci && npm run build"
start = "npm run start"
