# backend/nixpacks.toml
# ΜΟΝΟ python provider -> δεν εγκαθιστά δικό του Node/NPM ο Nixpacks
providers = ["python"]

[phases.setup]
# Εγκαθιστούμε ΜΙΑ φορά Node 20 από nixpkgs για να χτίσουμε το Vite
nixPkgs = ["nodejs_20"]

[phases.install]
commands = [
  "pip install -r requirements.txt",
  "cd ../frontend && npm ci"
]

[phases.build]
commands = [
  # Build του Vite SPA
  "cd ../frontend && npm run build",
  # Αντιγραφή assets στο Django static
  "rm -rf static/spa && mkdir -p static/spa",
  "cp -r ../frontend/dist/assets static/spa/",
  # Γράφουμε index.html στα templates με rewrite των assets σε /static/spa/assets/
  "mkdir -p templates",
  "sed 's|/assets/|/static/spa/assets/|g' ../frontend/dist/index.html > templates/index.html",

  # Django housekeeping
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
